export default {
  // Background Colors
  DARK_BACKGROUND: `#14002f`,
  LIGHT_BACKGROUND: `#EFF3F8`,

  // Foreground Colors
  DARK_FOREGROUND: `#000000`,
  LIGHT_FOREGROUND: `#FFFFFF`,

  // Primary Colors
  DARK_PRIMARY: `#FFFFFF`,
  LIGHT_PRIMARY: `#14002f`,

  // Inverse Colors
  DARK_INVERSE: `#14002f`,
  LIGHT_INVERSE: `#FFFFFF`,

  // Input
  DARK_INPUT_PLACEHOLDER: `#CCCCCC`,
  LIGHT_INPUT_PLACEHOLDER: `#666666`,

  // Other Colors
  WHITE: `#FFFFFF`,
  BLACK: `#000000`,
  BRAND_COLOR: `#4B286D`,
  OPAQUE_BRAND: `rgba(96,57,169, 0.5)`,
  TWITTER_COLOR: `#1A91DA`,
  GITHUB_COLOR: `#562676`,
  LINKEDIN_COLOR: `#0077B5`,
  VALID_GREEN: '#23DC3D',
  INVALID_RED: '#EC3B5A'
}
